### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by gioxx** [AlexStormwood/CommitsWithinTime#4]
Hi Alex, it's me again 😄 
I wanted to report that GitHub now insists on a warning as per the subject of this discussion:
`Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

I have already checked my scripts but no one use old method to talk with GitHub ENV/OUTPUT/..., can you please confirm that this behaviour is not originated by your Action?

Thanks again a lot and have a nice weekend.
Giovanni.

**Comment by AlexStormwood** [comment]
Somehow completely missed this - thankyou for noting this, I'll have a look at this during the week. Definitely seems like I need to do some updating to this action!

**Comment by AlexStormwood** [comment]
Action updated, and it works locally (in this repo's own action that uses itself) but I don't have any actively-developed projects using this action to confirm if the updates are practical beyond that. Looks like the deprecation warning should be gone, I think?

So, if you update to a newer version of this package, please make a new issue for any hiccups with the update. Thankyou :)
